apiVersion: v1
kind: Pod
metadata:
  name: my-pod-cka
spec:
  volumes:
  - name: killvol
    persistentVolumeClaim:
      claimName: my-pvc-cka
  containers:
  - name: pod
    image: nginx
    volumeMounts:
    - mountPath: /var/www/html
      name: killvol