apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-web-app-deployment
  name: my-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-web-app-deployment
    spec:
      containers:
      - image: wordpress
        name: wordpress
        resources: {}
status: {}