apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: red-pvc-cka
spec:
  accessModes:
     - ReadWriteOnce
  resources:
     requests:
       storage: 30Mi
  storageClassName: manual