apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: os
  name: ubuntu-pod
spec:
  containers:
  - image: ubuntu
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}