apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-cka
spec:
  volumes:
    - name: kill-vol
      persistentVolumeClaim:
        claimName: nginx-pvc-cka
  containers:
    - name: my-container
      image: nginx:latest
      volumeMounts:
        - mountPath: "/var/www/html"
          name: kill-vol
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"