apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"my-pvc-cka","namespace":"default"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"100Mi"}},"storageClassName":"standard","volumeName":"my-pv-cka"}}
    creationTimestamp: "2024-12-27T09:18:19Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: my-pvc-cka
    namespace: default
    resourceVersion: "2103"
    uid: 1a96770b-92cf-43c9-b367-e0b7d2ab6d37
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: my-pv-cka
  status:
    phase: Pending
kind: List
metadata:
  resourceVersion: ""